"""add_vendor_fields_payment_terms_tax_id_notes_address

Revision ID: 15a46ec27bb8
Revises: 43c59cc3b8a3
Create Date: 2025-11-28 06:00:23.545392

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15a46ec27bb8'
down_revision: Union[str, None] = '43c59cc3b8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('payment_terms', sa.String(length=100), nullable=True))
    op.add_column('vendors', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.add_column('vendors', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'notes')
    op.drop_column('vendors', 'tax_id')
    op.drop_column('vendors', 'payment_terms')
    op.drop_column('vendors', 'address')
    # ### end Alembic commands ###


