"""add_vendor_fields_payment_terms_tax_id_notes_address

Revision ID: 15a46ec27bb8
Revises: 43c59cc3b8a3
Create Date: 2025-11-28 06:00:23.545392

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15a46ec27bb8'
down_revision: Union[str, None] = '43c59cc3b8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if vendors table exists before modifying
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'vendors' in tables:
        columns = [col['name'] for col in inspector.get_columns('vendors')]
        if 'address' not in columns:
            op.add_column('vendors', sa.Column('address', sa.Text(), nullable=True))
        if 'payment_terms' not in columns:
            op.add_column('vendors', sa.Column('payment_terms', sa.String(length=100), nullable=True))
        if 'tax_id' not in columns:
            op.add_column('vendors', sa.Column('tax_id', sa.String(length=50), nullable=True))
        if 'notes' not in columns:
            op.add_column('vendors', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'notes')
    op.drop_column('vendors', 'tax_id')
    op.drop_column('vendors', 'payment_terms')
    op.drop_column('vendors', 'address')
    # ### end Alembic commands ###


