"""create orgs table

Revision ID: 3fb179632ef5
Revises: c9c13f89943b
Create Date: 2025-08-22 18:43:03.328672

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fb179632ef5'
down_revision: Union[str, None] = 'c9c13f89943b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


