"""add_vendor_qualifications_table

Revision ID: 43c59cc3b8a3
Revises: bcedbe25bb73
Create Date: 2025-11-28 05:49:27.604685

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '43c59cc3b8a3'
down_revision: Union[str, None] = 'bcedbe25bb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('financial_stability', sa.String(length=50), nullable=True, comment='Financial stability rating: excellent, good, fair, poor'),
    sa.Column('credentials_verified', sa.Boolean(), nullable=False, comment='Whether vendor credentials have been verified'),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of certifications (e.g., ISO 9001, ISO 27001)'),
    sa.Column('qualification_score', sa.String(length=10), nullable=True, comment='Overall qualification score (0-100)'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='Risk level: low, medium, high'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional qualification notes'),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_qualifications_assessed_by'), 'vendor_qualifications', ['assessed_by'], unique=False)
    op.create_index(op.f('ix_vendor_qualifications_id'), 'vendor_qualifications', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_qualifications_vendor_id'), 'vendor_qualifications', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_qualifications_vendor_id'), table_name='vendor_qualifications')
    op.drop_index(op.f('ix_vendor_qualifications_id'), table_name='vendor_qualifications')
    op.drop_index(op.f('ix_vendor_qualifications_assessed_by'), table_name='vendor_qualifications')
    op.drop_table('vendor_qualifications')
    # ### end Alembic commands ###


