"""Add short_id to users table

Revision ID: 5e5bff545a73
Revises: 8148e4713af7
Create Date: 2025-10-23 04:19:07.542008

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e5bff545a73'
down_revision: Union[str, None] = '8148e4713af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_overviews')
    op.drop_index(op.f('idx_opportunity_strategies_opportunity_id'), table_name='opportunity_strategies')
    op.drop_table('opportunity_strategies')
    op.drop_index(op.f('idx_opportunity_competitors_opportunity_id'), table_name='opportunity_competitors')
    op.drop_table('opportunity_competitors')
    op.drop_table('opportunity_documents')
    op.drop_index(op.f('idx_opportunity_stakeholders_opportunity_id'), table_name='opportunity_stakeholders')
    op.drop_table('opportunity_stakeholders')
    op.drop_index(op.f('idx_opportunity_drivers_opportunity_id'), table_name='opportunity_drivers')
    op.drop_table('opportunity_drivers')
    
    # Add short_id column as nullable first
    op.add_column('users', sa.Column('short_id', sa.String(length=10), nullable=True))
    
    # Generate short_id for existing users
    import random
    import string
    from sqlalchemy import text
    
    def generate_short_id():
        return ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
    
    # Get connection and update existing users
    connection = op.get_bind()
    
    # Get all existing users
    result = connection.execute(text("SELECT id FROM users WHERE short_id IS NULL"))
    users = result.fetchall()
    
    # Generate unique short_id for each user
    used_ids = set()
    for user in users:
        while True:
            short_id = generate_short_id()
            if short_id not in used_ids:
                # Check if it exists in database
                existing = connection.execute(text("SELECT id FROM users WHERE short_id = :short_id"), {"short_id": short_id}).fetchone()
                if not existing:
                    used_ids.add(short_id)
                    connection.execute(text("UPDATE users SET short_id = :short_id WHERE id = :user_id"), 
                                    {"short_id": short_id, "user_id": user[0]})
                    break
    
    # Now make the column NOT NULL
    op.alter_column('users', 'short_id', nullable=False)
    op.create_index(op.f('ix_users_short_id'), 'users', ['short_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_short_id'), table_name='users')
    op.drop_column('users', 'short_id')
    op.create_table('opportunity_drivers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_drivers_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_drivers_pkey'))
    )
    op.create_index(op.f('idx_opportunity_drivers_opportunity_id'), 'opportunity_drivers', ['opportunity_id'], unique=False)
    op.create_table('opportunity_stakeholders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('influence_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_stakeholders_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_stakeholders_pkey'))
    )
    op.create_index(op.f('idx_opportunity_stakeholders_opportunity_id'), 'opportunity_stakeholders', ['opportunity_id'], unique=False)
    op.create_table('opportunity_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'uploaded'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_available_for_proposal', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_documents_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_documents_pkey'))
    )
    op.create_table('opportunity_competitors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('strength', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('weakness', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_competitors_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_competitors_pkey'))
    )
    op.create_index(op.f('idx_opportunity_competitors_opportunity_id'), 'opportunity_competitors', ['opportunity_id'], unique=False)
    op.create_table('opportunity_strategies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_strategies_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_strategies_pkey'))
    )
    op.create_index(op.f('idx_opportunity_strategies_opportunity_id'), 'opportunity_strategies', ['opportunity_id'], unique=False)
    op.create_table('opportunity_overviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_scope', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('key_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('documents_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_overviews_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_overviews_pkey'))
    )
    # ### end Alembic commands ###


