"""Add opportunity documents table

Revision ID: 8148e4713af7
Revises: 41bfcd6801ca
Create Date: 2025-10-18 04:21:30.667001

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8148e4713af7'
down_revision: Union[str, None] = '41bfcd6801ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_strategies_opportunity_id'), table_name='opportunity_strategies')
    op.drop_table('opportunity_strategies')
    op.drop_index(op.f('ix_opportunity_legal_checklists_opportunity_id'), table_name='opportunity_legal_checklists')
    op.drop_table('opportunity_legal_checklists')
    op.drop_index(op.f('ix_opportunity_risks_opportunity_id'), table_name='opportunity_risks')
    op.drop_table('opportunity_risks')
    op.drop_index(op.f('ix_opportunity_overviews_opportunity_id'), table_name='opportunity_overviews')
    op.drop_table('opportunity_overviews')
    op.drop_index(op.f('ix_opportunity_financials_opportunity_id'), table_name='opportunity_financials')
    op.drop_table('opportunity_financials')
    op.drop_index(op.f('ix_opportunity_team_members_opportunity_id'), table_name='opportunity_team_members')
    op.drop_table('opportunity_team_members')
    op.drop_index(op.f('ix_opportunity_stakeholders_opportunity_id'), table_name='opportunity_stakeholders')
    op.drop_table('opportunity_stakeholders')
    op.drop_index(op.f('ix_opportunity_references_opportunity_id'), table_name='opportunity_references')
    op.drop_table('opportunity_references')
    op.drop_index(op.f('ix_opportunity_drivers_opportunity_id'), table_name='opportunity_drivers')
    op.drop_table('opportunity_drivers')
    op.drop_index(op.f('ix_opportunity_competitors_opportunity_id'), table_name='opportunity_competitors')
    op.drop_table('opportunity_competitors')
    op.drop_index(op.f('ix_opportunity_delivery_models_opportunity_id'), table_name='opportunity_delivery_models')
    op.drop_table('opportunity_delivery_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_delivery_models',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('approach', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_phases', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('identified_gaps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_delivery_models_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_delivery_models_pkey'))
    )
    op.create_index(op.f('ix_opportunity_delivery_models_opportunity_id'), 'opportunity_delivery_models', ['opportunity_id'], unique=False)
    op.create_table('opportunity_competitors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('threat_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('weaknesses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_competitors_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_competitors_pkey'))
    )
    op.create_index(op.f('ix_opportunity_competitors_opportunity_id'), 'opportunity_competitors', ['opportunity_id'], unique=False)
    op.create_table('opportunity_drivers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_drivers_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_drivers_pkey'))
    )
    op.create_index(op.f('ix_opportunity_drivers_opportunity_id'), 'opportunity_drivers', ['opportunity_id'], unique=False)
    op.create_table('opportunity_references',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_references_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_references_pkey'))
    )
    op.create_index(op.f('ix_opportunity_references_opportunity_id'), 'opportunity_references', ['opportunity_id'], unique=False)
    op.create_table('opportunity_stakeholders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('influence_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_stakeholders_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_stakeholders_pkey'))
    )
    op.create_index(op.f('ix_opportunity_stakeholders_opportunity_id'), 'opportunity_stakeholders', ['opportunity_id'], unique=False)
    op.create_table('opportunity_team_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('experience', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('availability', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_team_members_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_team_members_pkey'))
    )
    op.create_index(op.f('ix_opportunity_team_members_opportunity_id'), 'opportunity_team_members', ['opportunity_id'], unique=False)
    op.create_table('opportunity_financials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_project_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('budget_categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('contingency_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('profit_margin_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_financials_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_financials_pkey'))
    )
    op.create_index(op.f('ix_opportunity_financials_opportunity_id'), 'opportunity_financials', ['opportunity_id'], unique=False)
    op.create_table('opportunity_overviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_scope', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('key_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('documents_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_overviews_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_overviews_pkey'))
    )
    op.create_index(op.f('ix_opportunity_overviews_opportunity_id'), 'opportunity_overviews', ['opportunity_id'], unique=False)
    op.create_table('opportunity_risks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('risk_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('impact_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('probability', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mitigation_strategy', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_risks_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_risks_pkey'))
    )
    op.create_index(op.f('ix_opportunity_risks_opportunity_id'), 'opportunity_risks', ['opportunity_id'], unique=False)
    op.create_table('opportunity_legal_checklists',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_legal_checklists_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_legal_checklists_pkey'))
    )
    op.create_index(op.f('ix_opportunity_legal_checklists_opportunity_id'), 'opportunity_legal_checklists', ['opportunity_id'], unique=False)
    op.create_table('opportunity_strategies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_strategies_opportunity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_strategies_pkey'))
    )
    op.create_index(op.f('ix_opportunity_strategies_opportunity_id'), 'opportunity_strategies', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


