"""add_is_active_and_assessment_type_to_vendor_qualifications

Revision ID: 858159ac3384
Revises: 15a46ec27bb8
Create Date: 2025-11-28 06:28:16.616045

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '858159ac3384'
down_revision: Union[str, None] = '15a46ec27bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_active column as nullable first
    op.add_column('vendor_qualifications', sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether this is the current/active qualification (latest one)'))
    # Set default value for existing records (mark all as active since they're the only ones)
    op.execute("UPDATE vendor_qualifications SET is_active = TRUE WHERE is_active IS NULL")
    # Now make it NOT NULL
    op.alter_column('vendor_qualifications', 'is_active', nullable=False)
    # Add assessment_type column
    op.add_column('vendor_qualifications', sa.Column('assessment_type', sa.String(length=50), nullable=True, comment='Type of assessment: manual, ai_auto, periodic_review, etc.'))
    op.create_index(op.f('ix_vendor_qualifications_is_active'), 'vendor_qualifications', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_qualifications_is_active'), table_name='vendor_qualifications')
    op.drop_column('vendor_qualifications', 'assessment_type')
    op.drop_column('vendor_qualifications', 'is_active')
    # ### end Alembic commands ###


