"""add organization_id to accounts table

Revision ID: 86256bdba01e
Revises: 5ae020ae8f4f
Create Date: 2025-09-01 21:10:22.932388

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86256bdba01e'
down_revision: Union[str, None] = '5ae020ae8f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


