"""create orgs table

Revision ID: 925c9948af9f
Revises: a316a355b476
Create Date: 2025-08-22 12:03:02.898752

"""
from __future__ import annotations

from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import UUID
from alembic import op
import sqlalchemy as sa


revision: str = '925c9948af9f'
down_revision: Union[str, None] = 'a316a355b476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orgs",
        sa.Column(
            "org_id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.String(), unique=True, index=True, nullable=False),
        sa.Column("gid", sa.String(255), index=True, nullable=False, unique=True)

        
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orgs")
    # ### end Alembic commands ###


