"""create organization table

Revision ID: 9e16cf3152ff
Revises: a8c77cc72804
Create Date: 2025-08-22 11:08:46.265526

"""
from __future__ import annotations

from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import UUID
from alembic import op
import sqlalchemy as sa


revision: str = '9e16cf3152ff'
down_revision: Union[str, None] = 'a8c77cc72804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    op.create_table(
        "orgs",
        sa.Column(
            "org_id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.String(), unique=True, index=True, nullable=False),
        sa.Column("gid", UUID(as_uuid=True), unique=True, index=True,nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orgs")
    # ### end Alembic commands ###


