"""make_vendor_password_hash_nullable

Revision ID: bcedbe25bb73
Revises: f69e129dbc00
Create Date: 2025-11-28 05:16:23.856072

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bcedbe25bb73'
down_revision: Union[str, None] = 'f69e129dbc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if vendors table exists before modifying
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'vendors' in tables:
        op.alter_column('vendors', 'password_hash',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


