"""add account_notes table

Revision ID: c1e315f206fa
Revises: 4288e8217bf0
Create Date: 2025-09-12 03:31:55.979449

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1e315f206fa'
down_revision: Union[str, None] = '4288e8217bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_notes_account_id'), 'account_notes', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_notes_id'), 'account_notes', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_notes_id'), table_name='account_notes')
    op.drop_index(op.f('ix_account_notes_account_id'), table_name='account_notes')
    op.drop_table('account_notes')
    # ### end Alembic commands ###


