"""rename user_roles table to user_permissions

Revision ID: c5d2c5061ca1
Revises: 090f6d18782e
Create Date: 2025-09-04 14:22:35.337088

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5d2c5061ca1'
down_revision: Union[str, None] = '090f6d18782e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the table from user_roles to user_permissions
    op.rename_table('user_roles', 'user_permissions')
    
    # Rename the index
    op.execute('ALTER INDEX ix_user_roles_userid RENAME TO ix_user_permissions_userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the index back
    op.execute('ALTER INDEX ix_user_permissions_userid RENAME TO ix_user_roles_userid')
    
    # Rename the table back from user_permissions to user_roles
    op.rename_table('user_permissions', 'user_roles')
    # ### end Alembic commands ###


