"""add_name_to_users_table

Revision ID: d34039d97e31
Revises: 27y2jabi8qf1
Create Date: 2025-10-25 19:30:25.504275

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd34039d97e31'
down_revision: Union[str, None] = '27y2jabi8qf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the name column to users table
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the name column from users table
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
