"""create organizations table

Revision ID: dddae92f1e2d
Revises: 2d73d73eb79e
Create Date: 2025-08-22 10:21:43.840002

"""

from __future__ import annotations

from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import UUID
from alembic import op
import sqlalchemy as sa


revision: str = "dddae92f1e2d"
down_revision: Union[str, None] = "2d73d73eb79e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orgs",
        sa.Column(
            "org_id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.String(), unique=True, index=True, nullable=False),
        sa.Column("gid", UUID(as_uuid=True), unique=True, index=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orgs")
    # ### end Alembic commands ###
