"""create users table

Revision ID: fb52119575ae
Revises: dddae92f1e2d
Create Date: 2025-08-22 10:43:38.974420

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb52119575ae'
down_revision: Union[str, None] = 'dddae92f1e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gid', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_gid'), 'users', ['gid'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_orgs_gid'), table_name='orgs')
    op.drop_index(op.f('ix_orgs_name'), table_name='orgs')
    op.drop_table('orgs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('org_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gid', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('org_id', name=op.f('orgs_pkey'))
    )
    op.create_index(op.f('ix_orgs_name'), 'orgs', ['name'], unique=True)
    op.create_index(op.f('ix_orgs_gid'), 'orgs', ['gid'], unique=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_gid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


